columns:
  - Gender: int64
  - Age: int64
  - Heart rate: int64
  - Systolic blood pressure: int64
  - Diastolic blood pressure: int64
  - Blood sugar: float64
  - CK-MB: float64
  - Troponin: float64
  - Result: object

numerical_columns:
  - Age
  - Heart rate
  - Systolic blood pressure
  - Diastolic blood pressure
  - Blood sugar
  - CK-MB
  - Troponin

categorical_columns:
  - Result

# for data transformation
num_features:
  - Age
  - Heart rate
  - Systolic blood pressure
  - Diastolic blood pressure
  - Blood sugar
  - CK-MB
  - Troponin

mm_columns:
  - Age
  - Heart rate
  - Systolic blood pressure
  - Diastolic blood pressure
  - Blood sugar
  - CK-MB
  - Troponin
